token:
eventLoop:
  timer:
    afterRestart: 60
    delay: 20

mysql:
  use: false
  ip: 'localhost'
  user: 'root'
  password: 'root'
  database: 'hypixel'

shop:
  activate: true
  menuRows: 3
  menuTitle: '&bShop'
  categories:
    VIPS:
      ID: 57
      name: '&bVIPS'
      lore:
        - '&bwww.vitorblog.com'
      slot: 13
      menuRows: 3
      menuTitle: '&bVIPS &8» &7DESCONTO DE 50% EM TUDO!'
      items:
        VipFerro:
          ID: 57
          name: '&bVIP <Coloque um nome genérico aqui>'
          lore:
            - '&bwww.vitorblog.com'
          slot: 13
          price: 5 #Points
          commands:
            - 'give %player% diamond'

messages:
  points: '&bYou have %points% points'
  needPoints: '&bYou need %price% points to buy %item%'
  buy: '&bYou buy %item% (%price%)'
  broadcastBuy: '&b%player% buy %item% (%price%)' #Leave empty to disable broadcast