name: BlogMineShop
description: Mod do plugin oficial do MineShop
version: 1.0.1
main: com.vitorblog.mineshop.Main
load: POSTWORLD
authors: [Vitorblog <eu@vitorblog.com>, Sapiente <contato@clayderson.com.br>]
website: https://github.com/VitorBlog/spigot
softdepend: [MVdWPlaceholderAPI, PlaceholderAPI]
commands:
  mineshop:
  shop:
    aliases: [lojadepontos]
  points:
    aliases: [pontos,cash]
